# 1. Вибираємо базовий Python-образ
FROM python:3.11-slim

# 2. Встановлюємо робочу директорію всередині контейнера
WORKDIR /app

# 3. Копіюємо файли проєкту в контейнер
COPY . .
# 4. Встановлюємо залежності
RUN pip install --no-cache-dir -r requirements.txt

# 5. Вказуємо команду, що буде запускатися при старті контейнера
CMD ["python", "hw1_from_core_with_poetry.py"]
